version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/build-clio/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/build-docker-image/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/cmake/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/code-coverage/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/conan/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/create-issue/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/get-threads-number/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/git-common-ancestor/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/restore-cache/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop

  - package-ecosystem: github-actions
    directory: .github/actions/save-cache/
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/GMT
    reviewers:
      - XRPLF/clio-dev-team
    commit-message:
      prefix: "ci: [DEPENDABOT] "
    target-branch: develop
