version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/GMT"
    reviewers:
      - "godexsoft"
      - "kuznetsss"
      - "PeterChen13579"
    commit-message:
      prefix: "[CI] "
    target-branch: "develop"
