coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%

    patch:
      default:
        target: 20% # Need to bump this number https://docs.codecov.com/docs/commit-status#patch-status
        threshold: 2%

# `codecov/codecov-action` reruns `gcovr` if build files present
# That's why we run it in a separate workflow
# This ignore list is not currently used
#
# More info: https://github.com/XRPLF/clio/pull/2066
ignore:
  - "benchmarks"
  - "tests"
  - "src/data/cassandra/"
  - "src/data/CassandraBackend.hpp"
  - "src/data/BackendFactory.*"
