FROM ubuntu:20.04

COPY ./clio_server /opt/clio/bin/clio_server

RUN useradd -ms /bin/bash clio

USER clio
WORKDIR /home/clio

ENTRYPOINT ["/opt/clio/bin/clio_server", "--config", "/opt/clio/etc/config.json"]
