name: Setup conan
description: Setup conan profiles and artifactory on macOS runner

inputs:
  conan_files_dir:
    description: Directory with conan files
    required: true

runs:
  using: composite
  steps:
    - name: Fail on non-macOS
      if: runner.os != 'macOS'
      shell: bash
      run: exit 1

    - name: Copy global.conf
      shell: bash
      run: |
        cp "${{ inputs.conan_files_dir }}/global.conf" "${{ env.CONAN_HOME }}/global.conf"

    - name: Create apple-clang conan profile
      shell: bash
      run: |
        mkdir -p "${{ env.CONAN_HOME }}/profiles"
        cp .github/actions/setup_conan_macos/apple-clang.profile "${{ env.CONAN_HOME }}/profiles/apple-clang"

    - name: Create conan profiles for sanitizers
      shell: bash
      working-directory: ${{ inputs.conan_files_dir }}
      run: |
        cp ./sanitizer_template.profile "${{ env.CONAN_HOME }}/profiles/apple-clang.asan"
        cp ./sanitizer_template.profile "${{ env.CONAN_HOME }}/profiles/apple-clang.tsan"
        cp ./sanitizer_template.profile "${{ env.CONAN_HOME }}/profiles/apple-clang.ubsan"

    - name: Add artifactory remote
      shell: bash
      run: |
        conan remote add --index 0 ripple http://18.143.149.228:8081/artifactory/api/conan/dev
