name: Install packages
description: Install packages and do all other paltform specific preparations
runs:
  using: composite
  steps:
    - name: Install packages on mac
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
          brew install llvm@14 pkg-config ninja bison cmake ccache jq

    - name: Install packages on linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
          echo 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-17 main' >> /etc/apt/sources.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
          apt update -qq
          apt install -y jq clang-tidy-17

    - name: Install ccache on Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
          wget https://github.com/ccache/ccache/releases/download/v4.8.3/ccache-4.8.3-linux-x86_64.tar.xz
          tar xf ./ccache-4.8.3-linux-x86_64.tar.xz
          mv ./ccache-4.8.3-linux-x86_64/ccache /usr/bin/ccache

    - name: Fix git permissions on Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: git config --global --add safe.directory $PWD
