scrape_configs:
- job_name: clio
  scrape_interval: 5s
  scrape_timeout: 5s
  authorization:
    type: Password
    credentials: xrp
  static_configs:
  - targets:
    -  host.docker.internal:51233
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - localhost:9090
