name: Restore cache
description: Find and restores conan and ccache cache
inputs:
  conan_dir:
    description: Path to .conan directory
    required: true
  ccache_dir:
    description: Path to .ccache directory
    required: true
outputs:
  conan_cache_hit:
    description: Whether conan cache is being used
    value: ${{ steps.provide_output.outputs.conan_cache_hit }}
runs:
  using: composite
  steps:
    - name: Find common commit
      id: git_common_ancestor
      uses: ./.github/actions/git_common_ancestor

    - name: Restore conan cache
      uses: actions/cache/restore@v3
      id: conan_cache
      with:
        path: ${{ inputs.conan_dir }}/data
        key: clio-conan_data-${{ runner.os }}-develop-${{ hashFiles('./conanfile.py') }}

    - name: Restore ccache cache
      uses: actions/cache/restore@v3
      with:
        path: ${{ inputs.ccache_dir }}
        key: clio-ccache-${{ runner.os }}-develop-${{ steps.git_common_ancestor.outputs.commit }}

    - name: Provide output
      id: provide_output
      shell: bash
      run: echo "conan_cache_hit=${{ steps.conan_cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT


