name: Restore cache
description: Find and restores conan and ccache cache
inputs:
  conan_dir:
    description: Path to .conan directory
    required: true
  ccache_dir:
    description: Path to .ccache directory
    required: true
runs:
  using: composite
  steps:
    - name: Find common commit
      id: git_common_ancestor
      uses: ./.github/actions/git_common_ancestor

    - name: Restore conan cache
      uses: actions/cache/restore@v3
      id: conan_cache
      with:
        path: ${{ inputs.conan_dir }}/data
        key: clio-conan_data-${{ runner.os }}-develop-${{ hashFiles('./conanfile.py') }}

    - name: Restore ccache cache
      uses: actions/cache/restore@v3
      with:
        path: ${{ inputs.ccache_dir }}
        key: clio-ccache-${{ runner.os }}-develop-${{ steps.git_common_ancestor.outputs.commit }}
