set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/XRPLF/clio")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Ripple Labs Inc. <support@ripple.com>")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA ${CMAKE_SOURCE_DIR}/cmake/pkg/postinst)

if (PKG_RELEASE GREATER 0)
  set(CPACK_DEBIAN_PACKAGE_RELEASE ${PKG_RELEASE} CACHE STRING "Debian package release number")
endif ()

if (DEFINED PRE_TYPE)
  string(REPLACE "-" "~" CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
endif ()
