{
 "title": "Clio",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"clio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"clio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "work_queue_current_size{job=\"clio\"}",
     "legendFormat": "work queue size"
    }
   ]
  },
  {
   "title": "RPC Method Call Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rpc_method_duration_us{job=\"clio\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC Method Call Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(rpc_method_total_number{job=\"clio\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "RPC Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(rpc_error_total_number{job=\"clio\"}[$__rate_interval])",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Ledger Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ledger_cache_counter_total_number{job=\"clio\",type=\"cache_hit\"}[1m])) / sum(increase(ledger_cache_counter_total_number{job=\"clio\",type=\"request\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Completed Operations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(backend_operations_total_number{job=\"clio\",status=\"completed\"}[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Subscriptions Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "subscriptions_current_number{job=\"clio\"}",
     "legendFormat": "{{collection}}{{stream}}"
    }
   ]
  },
  {
   "title": "DB Opperations Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(backend_operations_total_number{job=\"clio\",status=~\"error|retry\"}[$__rate_interval])",
     "legendFormat": "{{operation}} {{status}}"
    },
    {
     "expr": "rate(backend_too_busy_total_number{job=\"clio\"}[$__rate_interval])",
     "legendFormat": "backend too_busy"
    }
   ]
  },
  {
   "title": "DB Pending operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "backend_operations_current_number{job=\"clio\",status=\"pending\"}",
     "legendFormat": "{{operation}}"
    },
    {}
   ]
  }
 ]
}