name: Git common ancestor
description: Find the closest common commit
outputs:
  commit:
    description: Hash of commit
    value: ${{ steps.find_common_ancestor.outputs.commit }}
runs:
  using: composite
  steps:
    - name: Find common git ancestor
      id: find_common_ancestor
      shell: bash
      env:
          BASE_BRANCH: ${{ github.base_ref || github.ref }}
      run: |
        common_ancestor=$(git merge-base --fork-point origin/$BASE_BRANCH)
        echo "commit=$common_ancestor" >> $GITHUB_OUTPUT
