name: Set environment variables
description: Set variables for conan and ccache
inputs:
  disable_ccache:
    description: Whether to disable ccache
    required: true
runs:
  using: composite
  steps:
    - name: Set env variables for macOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
        echo "CONAN_USER_HOME=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Set env variables for Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "CCACHE_DIR=/root/.ccache" >> $GITHUB_ENV
        echo "CONAN_USER_HOME=/root/" >> $GITHUB_ENV

    - name: Set CCACHE_DISABLE=1
      if: ${{ inputs.disable_ccache == 'true' }}
      shell: bash
      run: |
        echo "CCACHE_DISABLE=1" >> $GITHUB_ENV

