// Code generated by MockGen. DO NOT EDIT.
// Source: org/xrpl/rpc/v1/xrp_ledger_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	v1 "xrplf/clio/clio_snapshot/org/xrpl/rpc/v1"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockXRPLedgerAPIServiceClient is a mock of XRPLedgerAPIServiceClient interface.
type MockXRPLedgerAPIServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockXRPLedgerAPIServiceClientMockRecorder
}

// MockXRPLedgerAPIServiceClientMockRecorder is the mock recorder for MockXRPLedgerAPIServiceClient.
type MockXRPLedgerAPIServiceClientMockRecorder struct {
	mock *MockXRPLedgerAPIServiceClient
}

// NewMockXRPLedgerAPIServiceClient creates a new mock instance.
func NewMockXRPLedgerAPIServiceClient(ctrl *gomock.Controller) *MockXRPLedgerAPIServiceClient {
	mock := &MockXRPLedgerAPIServiceClient{ctrl: ctrl}
	mock.recorder = &MockXRPLedgerAPIServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXRPLedgerAPIServiceClient) EXPECT() *MockXRPLedgerAPIServiceClientMockRecorder {
	return m.recorder
}

// GetLedger mocks base method.
func (m *MockXRPLedgerAPIServiceClient) GetLedger(ctx context.Context, in *v1.GetLedgerRequest, opts ...grpc.CallOption) (*v1.GetLedgerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLedger", varargs...)
	ret0, _ := ret[0].(*v1.GetLedgerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedger indicates an expected call of GetLedger.
func (mr *MockXRPLedgerAPIServiceClientMockRecorder) GetLedger(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedger", reflect.TypeOf((*MockXRPLedgerAPIServiceClient)(nil).GetLedger), varargs...)
}

// GetLedgerData mocks base method.
func (m *MockXRPLedgerAPIServiceClient) GetLedgerData(ctx context.Context, in *v1.GetLedgerDataRequest, opts ...grpc.CallOption) (*v1.GetLedgerDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLedgerData", varargs...)
	ret0, _ := ret[0].(*v1.GetLedgerDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerData indicates an expected call of GetLedgerData.
func (mr *MockXRPLedgerAPIServiceClientMockRecorder) GetLedgerData(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerData", reflect.TypeOf((*MockXRPLedgerAPIServiceClient)(nil).GetLedgerData), varargs...)
}

// GetLedgerDiff mocks base method.
func (m *MockXRPLedgerAPIServiceClient) GetLedgerDiff(ctx context.Context, in *v1.GetLedgerDiffRequest, opts ...grpc.CallOption) (*v1.GetLedgerDiffResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLedgerDiff", varargs...)
	ret0, _ := ret[0].(*v1.GetLedgerDiffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerDiff indicates an expected call of GetLedgerDiff.
func (mr *MockXRPLedgerAPIServiceClientMockRecorder) GetLedgerDiff(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerDiff", reflect.TypeOf((*MockXRPLedgerAPIServiceClient)(nil).GetLedgerDiff), varargs...)
}

// GetLedgerEntry mocks base method.
func (m *MockXRPLedgerAPIServiceClient) GetLedgerEntry(ctx context.Context, in *v1.GetLedgerEntryRequest, opts ...grpc.CallOption) (*v1.GetLedgerEntryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLedgerEntry", varargs...)
	ret0, _ := ret[0].(*v1.GetLedgerEntryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerEntry indicates an expected call of GetLedgerEntry.
func (mr *MockXRPLedgerAPIServiceClientMockRecorder) GetLedgerEntry(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerEntry", reflect.TypeOf((*MockXRPLedgerAPIServiceClient)(nil).GetLedgerEntry), varargs...)
}

// MockXRPLedgerAPIServiceServer is a mock of XRPLedgerAPIServiceServer interface.
type MockXRPLedgerAPIServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockXRPLedgerAPIServiceServerMockRecorder
}

// MockXRPLedgerAPIServiceServerMockRecorder is the mock recorder for MockXRPLedgerAPIServiceServer.
type MockXRPLedgerAPIServiceServerMockRecorder struct {
	mock *MockXRPLedgerAPIServiceServer
}

// NewMockXRPLedgerAPIServiceServer creates a new mock instance.
func NewMockXRPLedgerAPIServiceServer(ctrl *gomock.Controller) *MockXRPLedgerAPIServiceServer {
	mock := &MockXRPLedgerAPIServiceServer{ctrl: ctrl}
	mock.recorder = &MockXRPLedgerAPIServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXRPLedgerAPIServiceServer) EXPECT() *MockXRPLedgerAPIServiceServerMockRecorder {
	return m.recorder
}

// GetLedger mocks base method.
func (m *MockXRPLedgerAPIServiceServer) GetLedger(arg0 context.Context, arg1 *v1.GetLedgerRequest) (*v1.GetLedgerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedger", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetLedgerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedger indicates an expected call of GetLedger.
func (mr *MockXRPLedgerAPIServiceServerMockRecorder) GetLedger(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedger", reflect.TypeOf((*MockXRPLedgerAPIServiceServer)(nil).GetLedger), arg0, arg1)
}

// GetLedgerData mocks base method.
func (m *MockXRPLedgerAPIServiceServer) GetLedgerData(arg0 context.Context, arg1 *v1.GetLedgerDataRequest) (*v1.GetLedgerDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerData", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetLedgerDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerData indicates an expected call of GetLedgerData.
func (mr *MockXRPLedgerAPIServiceServerMockRecorder) GetLedgerData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerData", reflect.TypeOf((*MockXRPLedgerAPIServiceServer)(nil).GetLedgerData), arg0, arg1)
}

// GetLedgerDiff mocks base method.
func (m *MockXRPLedgerAPIServiceServer) GetLedgerDiff(arg0 context.Context, arg1 *v1.GetLedgerDiffRequest) (*v1.GetLedgerDiffResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerDiff", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetLedgerDiffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerDiff indicates an expected call of GetLedgerDiff.
func (mr *MockXRPLedgerAPIServiceServerMockRecorder) GetLedgerDiff(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerDiff", reflect.TypeOf((*MockXRPLedgerAPIServiceServer)(nil).GetLedgerDiff), arg0, arg1)
}

// GetLedgerEntry mocks base method.
func (m *MockXRPLedgerAPIServiceServer) GetLedgerEntry(arg0 context.Context, arg1 *v1.GetLedgerEntryRequest) (*v1.GetLedgerEntryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerEntry", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetLedgerEntryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerEntry indicates an expected call of GetLedgerEntry.
func (mr *MockXRPLedgerAPIServiceServerMockRecorder) GetLedgerEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerEntry", reflect.TypeOf((*MockXRPLedgerAPIServiceServer)(nil).GetLedgerEntry), arg0, arg1)
}

// mustEmbedUnimplementedXRPLedgerAPIServiceServer mocks base method.
func (m *MockXRPLedgerAPIServiceServer) mustEmbedUnimplementedXRPLedgerAPIServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedXRPLedgerAPIServiceServer")
}

// mustEmbedUnimplementedXRPLedgerAPIServiceServer indicates an expected call of mustEmbedUnimplementedXRPLedgerAPIServiceServer.
func (mr *MockXRPLedgerAPIServiceServerMockRecorder) mustEmbedUnimplementedXRPLedgerAPIServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedXRPLedgerAPIServiceServer", reflect.TypeOf((*MockXRPLedgerAPIServiceServer)(nil).mustEmbedUnimplementedXRPLedgerAPIServiceServer))
}

// MockUnsafeXRPLedgerAPIServiceServer is a mock of UnsafeXRPLedgerAPIServiceServer interface.
type MockUnsafeXRPLedgerAPIServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeXRPLedgerAPIServiceServerMockRecorder
}

// MockUnsafeXRPLedgerAPIServiceServerMockRecorder is the mock recorder for MockUnsafeXRPLedgerAPIServiceServer.
type MockUnsafeXRPLedgerAPIServiceServerMockRecorder struct {
	mock *MockUnsafeXRPLedgerAPIServiceServer
}

// NewMockUnsafeXRPLedgerAPIServiceServer creates a new mock instance.
func NewMockUnsafeXRPLedgerAPIServiceServer(ctrl *gomock.Controller) *MockUnsafeXRPLedgerAPIServiceServer {
	mock := &MockUnsafeXRPLedgerAPIServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeXRPLedgerAPIServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeXRPLedgerAPIServiceServer) EXPECT() *MockUnsafeXRPLedgerAPIServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedXRPLedgerAPIServiceServer mocks base method.
func (m *MockUnsafeXRPLedgerAPIServiceServer) mustEmbedUnimplementedXRPLedgerAPIServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedXRPLedgerAPIServiceServer")
}

// mustEmbedUnimplementedXRPLedgerAPIServiceServer indicates an expected call of mustEmbedUnimplementedXRPLedgerAPIServiceServer.
func (mr *MockUnsafeXRPLedgerAPIServiceServerMockRecorder) mustEmbedUnimplementedXRPLedgerAPIServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedXRPLedgerAPIServiceServer", reflect.TypeOf((*MockUnsafeXRPLedgerAPIServiceServer)(nil).mustEmbedUnimplementedXRPLedgerAPIServiceServer))
}
