name: Build clio
description: Build clio in build directory
runs:
  using: composite
  steps:
    - name: Get number of threads
      uses: ./.github/actions/get_number_of_threads
      id: number_of_threads

    - name: Build Clio
      shell: bash
      run: |
        cd build
        cmake --build . --parallel ${{ steps.number_of_threads.outputs.threads_number }}
