// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: org/xrpl/rpc/v1/get_ledger_data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get ledger objects for a specific ledger. You can iterate through several
// calls to retrieve the entire contents of a single ledger version.
type GetLedgerDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, only objects with a key greater than marker are returned.
	// This can be used to pick up where a previous call left off.
	// Set marker to the value of marker in the previous response.
	Marker []byte           `protobuf:"bytes,1,opt,name=marker,proto3" json:"marker,omitempty"`
	Ledger *LedgerSpecifier `protobuf:"bytes,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	// If set, only objects with a key less than end_marker are returned
	EndMarker []byte `protobuf:"bytes,3,opt,name=end_marker,json=endMarker,proto3" json:"end_marker,omitempty"`
	// If the request needs to be forwarded from a reporting node to a p2p node,
	// the reporting node will set this field. Clients should not set this
	// field.
	ClientIp string `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// Identifying string. If user is set, client_ip is not set, and request is
	// coming from a secure_gateway host, then the client is not subject to
	// resource controls
	User          string `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerDataRequest) Reset() {
	*x = GetLedgerDataRequest{}
	mi := &file_org_xrpl_rpc_v1_get_ledger_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerDataRequest) ProtoMessage() {}

func (x *GetLedgerDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_ledger_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerDataRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerDataRequest) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetLedgerDataRequest) GetMarker() []byte {
	if x != nil {
		return x.Marker
	}
	return nil
}

func (x *GetLedgerDataRequest) GetLedger() *LedgerSpecifier {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *GetLedgerDataRequest) GetEndMarker() []byte {
	if x != nil {
		return x.EndMarker
	}
	return nil
}

func (x *GetLedgerDataRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *GetLedgerDataRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type GetLedgerDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence of the ledger containing the returned ledger objects
	LedgerIndex uint32 `protobuf:"varint,1,opt,name=ledger_index,json=ledgerIndex,proto3" json:"ledger_index,omitempty"`
	// Hash of the ledger containing the returned ledger objects
	LedgerHash []byte `protobuf:"bytes,2,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	// Ledger objects
	LedgerObjects *RawLedgerObjects `protobuf:"bytes,3,opt,name=ledger_objects,json=ledgerObjects,proto3" json:"ledger_objects,omitempty"`
	// Key to be passed into a subsequent call to continue iteration. If not
	// set, there are no more objects left in the ledger, or no more objects
	// with key less than end_marker (if end_marker was set in the request)
	Marker []byte `protobuf:"bytes,4,opt,name=marker,proto3" json:"marker,omitempty"`
	// True if request was exempt from resource controls
	IsUnlimited   bool `protobuf:"varint,7,opt,name=is_unlimited,json=isUnlimited,proto3" json:"is_unlimited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerDataResponse) Reset() {
	*x = GetLedgerDataResponse{}
	mi := &file_org_xrpl_rpc_v1_get_ledger_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerDataResponse) ProtoMessage() {}

func (x *GetLedgerDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_ledger_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerDataResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerDataResponse) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetLedgerDataResponse) GetLedgerIndex() uint32 {
	if x != nil {
		return x.LedgerIndex
	}
	return 0
}

func (x *GetLedgerDataResponse) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

func (x *GetLedgerDataResponse) GetLedgerObjects() *RawLedgerObjects {
	if x != nil {
		return x.LedgerObjects
	}
	return nil
}

func (x *GetLedgerDataResponse) GetMarker() []byte {
	if x != nil {
		return x.Marker
	}
	return nil
}

func (x *GetLedgerDataResponse) GetIsUnlimited() bool {
	if x != nil {
		return x.IsUnlimited
	}
	return false
}

var File_org_xrpl_rpc_v1_get_ledger_data_proto protoreflect.FileDescriptor

var file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70,
	0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72,
	0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x06, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72,
	0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x06, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x22, 0xe0, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x48, 0x0a, 0x0e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72,
	0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x77, 0x4c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x0d, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x72, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x55, 0x6e, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x65, 0x64, 0x42, 0x13, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescOnce sync.Once
	file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescData = file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDesc
)

func file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescGZIP() []byte {
	file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescOnce.Do(func() {
		file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescData)
	})
	return file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDescData
}

var file_org_xrpl_rpc_v1_get_ledger_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_xrpl_rpc_v1_get_ledger_data_proto_goTypes = []any{
	(*GetLedgerDataRequest)(nil),  // 0: org.xrpl.rpc.v1.GetLedgerDataRequest
	(*GetLedgerDataResponse)(nil), // 1: org.xrpl.rpc.v1.GetLedgerDataResponse
	(*LedgerSpecifier)(nil),       // 2: org.xrpl.rpc.v1.LedgerSpecifier
	(*RawLedgerObjects)(nil),      // 3: org.xrpl.rpc.v1.RawLedgerObjects
}
var file_org_xrpl_rpc_v1_get_ledger_data_proto_depIdxs = []int32{
	2, // 0: org.xrpl.rpc.v1.GetLedgerDataRequest.ledger:type_name -> org.xrpl.rpc.v1.LedgerSpecifier
	3, // 1: org.xrpl.rpc.v1.GetLedgerDataResponse.ledger_objects:type_name -> org.xrpl.rpc.v1.RawLedgerObjects
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_get_ledger_data_proto_init() }
func file_org_xrpl_rpc_v1_get_ledger_data_proto_init() {
	if File_org_xrpl_rpc_v1_get_ledger_data_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_ledger_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_xrpl_rpc_v1_get_ledger_data_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_get_ledger_data_proto_depIdxs,
		MessageInfos:      file_org_xrpl_rpc_v1_get_ledger_data_proto_msgTypes,
	}.Build()
	File_org_xrpl_rpc_v1_get_ledger_data_proto = out.File
	file_org_xrpl_rpc_v1_get_ledger_data_proto_rawDesc = nil
	file_org_xrpl_rpc_v1_get_ledger_data_proto_goTypes = nil
	file_org_xrpl_rpc_v1_get_ledger_data_proto_depIdxs = nil
}
