// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: org/xrpl/rpc/v1/get_ledger_diff.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get the state map difference between the two specified ledgers
type GetLedgerDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseLedger    *LedgerSpecifier       `protobuf:"bytes,1,opt,name=base_ledger,json=baseLedger,proto3" json:"base_ledger,omitempty"`
	DesiredLedger *LedgerSpecifier       `protobuf:"bytes,2,opt,name=desired_ledger,json=desiredLedger,proto3" json:"desired_ledger,omitempty"`
	// If true, include the full ledger object. If false, only keys are included.
	IncludeBlobs bool `protobuf:"varint,3,opt,name=include_blobs,json=includeBlobs,proto3" json:"include_blobs,omitempty"`
	// If the request needs to be forwarded from a reporting node to a p2p node,
	// the reporting node will set this field. Clients should not set this
	// field.
	ClientIp      string `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerDiffRequest) Reset() {
	*x = GetLedgerDiffRequest{}
	mi := &file_org_xrpl_rpc_v1_get_ledger_diff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerDiffRequest) ProtoMessage() {}

func (x *GetLedgerDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_ledger_diff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerDiffRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerDiffRequest) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescGZIP(), []int{0}
}

func (x *GetLedgerDiffRequest) GetBaseLedger() *LedgerSpecifier {
	if x != nil {
		return x.BaseLedger
	}
	return nil
}

func (x *GetLedgerDiffRequest) GetDesiredLedger() *LedgerSpecifier {
	if x != nil {
		return x.DesiredLedger
	}
	return nil
}

func (x *GetLedgerDiffRequest) GetIncludeBlobs() bool {
	if x != nil {
		return x.IncludeBlobs
	}
	return false
}

func (x *GetLedgerDiffRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type GetLedgerDiffResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All ledger objects that were added, modified or deleted between
	// base_ledger and desired_ledger
	LedgerObjects *RawLedgerObjects `protobuf:"bytes,1,opt,name=ledger_objects,json=ledgerObjects,proto3" json:"ledger_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerDiffResponse) Reset() {
	*x = GetLedgerDiffResponse{}
	mi := &file_org_xrpl_rpc_v1_get_ledger_diff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerDiffResponse) ProtoMessage() {}

func (x *GetLedgerDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_get_ledger_diff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerDiffResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerDiffResponse) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescGZIP(), []int{1}
}

func (x *GetLedgerDiffResponse) GetLedgerObjects() *RawLedgerObjects {
	if x != nil {
		return x.LedgerObjects
	}
	return nil
}

var File_org_xrpl_rpc_v1_get_ledger_diff_proto protoreflect.FileDescriptor

var file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x64, 0x69, 0x66,
	0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70,
	0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72,
	0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x41, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x4c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x12, 0x47, 0x0a, 0x0e, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0d, 0x64, 0x65,
	0x73, 0x69, 0x72, 0x65, 0x64, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x42, 0x6c, 0x6f, 0x62, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x22, 0x61, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x61, 0x77, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x52, 0x0d, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x42, 0x13, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescOnce sync.Once
	file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescData = file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDesc
)

func file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescGZIP() []byte {
	file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescOnce.Do(func() {
		file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescData)
	})
	return file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDescData
}

var file_org_xrpl_rpc_v1_get_ledger_diff_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_xrpl_rpc_v1_get_ledger_diff_proto_goTypes = []any{
	(*GetLedgerDiffRequest)(nil),  // 0: org.xrpl.rpc.v1.GetLedgerDiffRequest
	(*GetLedgerDiffResponse)(nil), // 1: org.xrpl.rpc.v1.GetLedgerDiffResponse
	(*LedgerSpecifier)(nil),       // 2: org.xrpl.rpc.v1.LedgerSpecifier
	(*RawLedgerObjects)(nil),      // 3: org.xrpl.rpc.v1.RawLedgerObjects
}
var file_org_xrpl_rpc_v1_get_ledger_diff_proto_depIdxs = []int32{
	2, // 0: org.xrpl.rpc.v1.GetLedgerDiffRequest.base_ledger:type_name -> org.xrpl.rpc.v1.LedgerSpecifier
	2, // 1: org.xrpl.rpc.v1.GetLedgerDiffRequest.desired_ledger:type_name -> org.xrpl.rpc.v1.LedgerSpecifier
	3, // 2: org.xrpl.rpc.v1.GetLedgerDiffResponse.ledger_objects:type_name -> org.xrpl.rpc.v1.RawLedgerObjects
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_get_ledger_diff_proto_init() }
func file_org_xrpl_rpc_v1_get_ledger_diff_proto_init() {
	if File_org_xrpl_rpc_v1_get_ledger_diff_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_ledger_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_xrpl_rpc_v1_get_ledger_diff_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_get_ledger_diff_proto_depIdxs,
		MessageInfos:      file_org_xrpl_rpc_v1_get_ledger_diff_proto_msgTypes,
	}.Build()
	File_org_xrpl_rpc_v1_get_ledger_diff_proto = out.File
	file_org_xrpl_rpc_v1_get_ledger_diff_proto_rawDesc = nil
	file_org_xrpl_rpc_v1_get_ledger_diff_proto_goTypes = nil
	file_org_xrpl_rpc_v1_get_ledger_diff_proto_depIdxs = nil
}
