// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: org/xrpl/rpc/v1/ledger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next field: 4
type LedgerSpecifier_Shortcut int32

const (
	LedgerSpecifier_SHORTCUT_UNSPECIFIED LedgerSpecifier_Shortcut = 0
	LedgerSpecifier_SHORTCUT_VALIDATED   LedgerSpecifier_Shortcut = 1
	LedgerSpecifier_SHORTCUT_CLOSED      LedgerSpecifier_Shortcut = 2
	LedgerSpecifier_SHORTCUT_CURRENT     LedgerSpecifier_Shortcut = 3
)

// Enum value maps for LedgerSpecifier_Shortcut.
var (
	LedgerSpecifier_Shortcut_name = map[int32]string{
		0: "SHORTCUT_UNSPECIFIED",
		1: "SHORTCUT_VALIDATED",
		2: "SHORTCUT_CLOSED",
		3: "SHORTCUT_CURRENT",
	}
	LedgerSpecifier_Shortcut_value = map[string]int32{
		"SHORTCUT_UNSPECIFIED": 0,
		"SHORTCUT_VALIDATED":   1,
		"SHORTCUT_CLOSED":      2,
		"SHORTCUT_CURRENT":     3,
	}
)

func (x LedgerSpecifier_Shortcut) Enum() *LedgerSpecifier_Shortcut {
	p := new(LedgerSpecifier_Shortcut)
	*p = x
	return p
}

func (x LedgerSpecifier_Shortcut) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerSpecifier_Shortcut) Descriptor() protoreflect.EnumDescriptor {
	return file_org_xrpl_rpc_v1_ledger_proto_enumTypes[0].Descriptor()
}

func (LedgerSpecifier_Shortcut) Type() protoreflect.EnumType {
	return &file_org_xrpl_rpc_v1_ledger_proto_enumTypes[0]
}

func (x LedgerSpecifier_Shortcut) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerSpecifier_Shortcut.Descriptor instead.
func (LedgerSpecifier_Shortcut) EnumDescriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_ledger_proto_rawDescGZIP(), []int{0, 0}
}

type RawLedgerObject_ModificationType int32

const (
	RawLedgerObject_UNSPECIFIED RawLedgerObject_ModificationType = 0
	RawLedgerObject_CREATED     RawLedgerObject_ModificationType = 1
	RawLedgerObject_MODIFIED    RawLedgerObject_ModificationType = 2
	RawLedgerObject_DELETED     RawLedgerObject_ModificationType = 3
)

// Enum value maps for RawLedgerObject_ModificationType.
var (
	RawLedgerObject_ModificationType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CREATED",
		2: "MODIFIED",
		3: "DELETED",
	}
	RawLedgerObject_ModificationType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CREATED":     1,
		"MODIFIED":    2,
		"DELETED":     3,
	}
)

func (x RawLedgerObject_ModificationType) Enum() *RawLedgerObject_ModificationType {
	p := new(RawLedgerObject_ModificationType)
	*p = x
	return p
}

func (x RawLedgerObject_ModificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RawLedgerObject_ModificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_org_xrpl_rpc_v1_ledger_proto_enumTypes[1].Descriptor()
}

func (RawLedgerObject_ModificationType) Type() protoreflect.EnumType {
	return &file_org_xrpl_rpc_v1_ledger_proto_enumTypes[1]
}

func (x RawLedgerObject_ModificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RawLedgerObject_ModificationType.Descriptor instead.
func (RawLedgerObject_ModificationType) EnumDescriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_ledger_proto_rawDescGZIP(), []int{1, 0}
}

// Next field: 4
type LedgerSpecifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ledger:
	//
	//	*LedgerSpecifier_Shortcut_
	//	*LedgerSpecifier_Sequence
	//	*LedgerSpecifier_Hash
	Ledger        isLedgerSpecifier_Ledger `protobuf_oneof:"ledger"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerSpecifier) Reset() {
	*x = LedgerSpecifier{}
	mi := &file_org_xrpl_rpc_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerSpecifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerSpecifier) ProtoMessage() {}

func (x *LedgerSpecifier) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerSpecifier.ProtoReflect.Descriptor instead.
func (*LedgerSpecifier) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerSpecifier) GetLedger() isLedgerSpecifier_Ledger {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *LedgerSpecifier) GetShortcut() LedgerSpecifier_Shortcut {
	if x != nil {
		if x, ok := x.Ledger.(*LedgerSpecifier_Shortcut_); ok {
			return x.Shortcut
		}
	}
	return LedgerSpecifier_SHORTCUT_UNSPECIFIED
}

func (x *LedgerSpecifier) GetSequence() uint32 {
	if x != nil {
		if x, ok := x.Ledger.(*LedgerSpecifier_Sequence); ok {
			return x.Sequence
		}
	}
	return 0
}

func (x *LedgerSpecifier) GetHash() []byte {
	if x != nil {
		if x, ok := x.Ledger.(*LedgerSpecifier_Hash); ok {
			return x.Hash
		}
	}
	return nil
}

type isLedgerSpecifier_Ledger interface {
	isLedgerSpecifier_Ledger()
}

type LedgerSpecifier_Shortcut_ struct {
	Shortcut LedgerSpecifier_Shortcut `protobuf:"varint,1,opt,name=shortcut,proto3,enum=org.xrpl.rpc.v1.LedgerSpecifier_Shortcut,oneof"`
}

type LedgerSpecifier_Sequence struct {
	Sequence uint32 `protobuf:"varint,2,opt,name=sequence,proto3,oneof"`
}

type LedgerSpecifier_Hash struct {
	// 32 bytes
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3,oneof"`
}

func (*LedgerSpecifier_Shortcut_) isLedgerSpecifier_Ledger() {}

func (*LedgerSpecifier_Sequence) isLedgerSpecifier_Ledger() {}

func (*LedgerSpecifier_Hash) isLedgerSpecifier_Ledger() {}

// Next field: 3
type RawLedgerObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw data of the ledger object. In GetLedgerResponse and
	// GetLedgerDiffResponse, data will be empty if the object was deleted.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Key of the ledger object
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Whether the object was created, modified or deleted
	ModType RawLedgerObject_ModificationType `protobuf:"varint,3,opt,name=mod_type,json=modType,proto3,enum=org.xrpl.rpc.v1.RawLedgerObject_ModificationType" json:"mod_type,omitempty"`
	// Key of the object preceding this object in the desired ledger
	Predecessor []byte `protobuf:"bytes,4,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	// Key of the object succeeding this object in the desired ledger
	Successor     []byte `protobuf:"bytes,5,opt,name=successor,proto3" json:"successor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawLedgerObject) Reset() {
	*x = RawLedgerObject{}
	mi := &file_org_xrpl_rpc_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawLedgerObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawLedgerObject) ProtoMessage() {}

func (x *RawLedgerObject) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawLedgerObject.ProtoReflect.Descriptor instead.
func (*RawLedgerObject) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *RawLedgerObject) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RawLedgerObject) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawLedgerObject) GetModType() RawLedgerObject_ModificationType {
	if x != nil {
		return x.ModType
	}
	return RawLedgerObject_UNSPECIFIED
}

func (x *RawLedgerObject) GetPredecessor() []byte {
	if x != nil {
		return x.Predecessor
	}
	return nil
}

func (x *RawLedgerObject) GetSuccessor() []byte {
	if x != nil {
		return x.Successor
	}
	return nil
}

type RawLedgerObjects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*RawLedgerObject     `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawLedgerObjects) Reset() {
	*x = RawLedgerObjects{}
	mi := &file_org_xrpl_rpc_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawLedgerObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawLedgerObjects) ProtoMessage() {}

func (x *RawLedgerObjects) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawLedgerObjects.ProtoReflect.Descriptor instead.
func (*RawLedgerObjects) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *RawLedgerObjects) GetObjects() []*RawLedgerObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

// Successor information for book directories. The book base is (usually) not
// an actual object, yet we need to be able to ask for the successor to the
// book base.
type BookSuccessor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base of the book in question
	BookBase []byte `protobuf:"bytes,1,opt,name=book_base,json=bookBase,proto3" json:"book_base,omitempty"`
	// First book directory in the book. An empty value here means the entire
	// book is deleted
	FirstBook     []byte `protobuf:"bytes,2,opt,name=first_book,json=firstBook,proto3" json:"first_book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSuccessor) Reset() {
	*x = BookSuccessor{}
	mi := &file_org_xrpl_rpc_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSuccessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSuccessor) ProtoMessage() {}

func (x *BookSuccessor) ProtoReflect() protoreflect.Message {
	mi := &file_org_xrpl_rpc_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSuccessor.ProtoReflect.Descriptor instead.
func (*BookSuccessor) Descriptor() ([]byte, []int) {
	return file_org_xrpl_rpc_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *BookSuccessor) GetBookBase() []byte {
	if x != nil {
		return x.BookBase
	}
	return nil
}

func (x *BookSuccessor) GetFirstBook() []byte {
	if x != nil {
		return x.FirstBook
	}
	return nil
}

var File_org_xrpl_rpc_v1_ledger_proto protoreflect.FileDescriptor

var file_org_xrpl_rpc_v1_ledger_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x72, 0x67, 0x2f, 0x78, 0x72, 0x70, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x22,
	0x81, 0x02, 0x0a, 0x0f, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x70,
	0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x75, 0x74,
	0x48, 0x00, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00,
	0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x22, 0x67, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x63, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x14,
	0x53, 0x48, 0x4f, 0x52, 0x54, 0x43, 0x55, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x48, 0x4f, 0x52, 0x54, 0x43,
	0x55, 0x54, 0x5f, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x53, 0x48, 0x4f, 0x52, 0x54, 0x43, 0x55, 0x54, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x48, 0x4f, 0x52, 0x54, 0x43, 0x55, 0x54, 0x5f,
	0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x42, 0x08, 0x0a, 0x06, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x22, 0x92, 0x02, 0x0a, 0x0f, 0x52, 0x61, 0x77, 0x4c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x4c, 0x0a,
	0x08, 0x6d, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x31, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x61, 0x77, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x22, 0x4b, 0x0a, 0x10, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x22, 0x4e, 0x0a, 0x10, 0x52, 0x61, 0x77, 0x4c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x07,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70, 0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x61, 0x77, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x4b, 0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x6b,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f,
	0x6b, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x6f,
	0x6f, 0x6b, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x42, 0x13, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x72, 0x70,
	0x6c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_org_xrpl_rpc_v1_ledger_proto_rawDescOnce sync.Once
	file_org_xrpl_rpc_v1_ledger_proto_rawDescData = file_org_xrpl_rpc_v1_ledger_proto_rawDesc
)

func file_org_xrpl_rpc_v1_ledger_proto_rawDescGZIP() []byte {
	file_org_xrpl_rpc_v1_ledger_proto_rawDescOnce.Do(func() {
		file_org_xrpl_rpc_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_xrpl_rpc_v1_ledger_proto_rawDescData)
	})
	return file_org_xrpl_rpc_v1_ledger_proto_rawDescData
}

var file_org_xrpl_rpc_v1_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_org_xrpl_rpc_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_org_xrpl_rpc_v1_ledger_proto_goTypes = []any{
	(LedgerSpecifier_Shortcut)(0),         // 0: org.xrpl.rpc.v1.LedgerSpecifier.Shortcut
	(RawLedgerObject_ModificationType)(0), // 1: org.xrpl.rpc.v1.RawLedgerObject.ModificationType
	(*LedgerSpecifier)(nil),               // 2: org.xrpl.rpc.v1.LedgerSpecifier
	(*RawLedgerObject)(nil),               // 3: org.xrpl.rpc.v1.RawLedgerObject
	(*RawLedgerObjects)(nil),              // 4: org.xrpl.rpc.v1.RawLedgerObjects
	(*BookSuccessor)(nil),                 // 5: org.xrpl.rpc.v1.BookSuccessor
}
var file_org_xrpl_rpc_v1_ledger_proto_depIdxs = []int32{
	0, // 0: org.xrpl.rpc.v1.LedgerSpecifier.shortcut:type_name -> org.xrpl.rpc.v1.LedgerSpecifier.Shortcut
	1, // 1: org.xrpl.rpc.v1.RawLedgerObject.mod_type:type_name -> org.xrpl.rpc.v1.RawLedgerObject.ModificationType
	3, // 2: org.xrpl.rpc.v1.RawLedgerObjects.objects:type_name -> org.xrpl.rpc.v1.RawLedgerObject
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_ledger_proto_init() }
func file_org_xrpl_rpc_v1_ledger_proto_init() {
	if File_org_xrpl_rpc_v1_ledger_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_ledger_proto_msgTypes[0].OneofWrappers = []any{
		(*LedgerSpecifier_Shortcut_)(nil),
		(*LedgerSpecifier_Sequence)(nil),
		(*LedgerSpecifier_Hash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_xrpl_rpc_v1_ledger_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_xrpl_rpc_v1_ledger_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_ledger_proto_depIdxs,
		EnumInfos:         file_org_xrpl_rpc_v1_ledger_proto_enumTypes,
		MessageInfos:      file_org_xrpl_rpc_v1_ledger_proto_msgTypes,
	}.Build()
	File_org_xrpl_rpc_v1_ledger_proto = out.File
	file_org_xrpl_rpc_v1_ledger_proto_rawDesc = nil
	file_org_xrpl_rpc_v1_ledger_proto_goTypes = nil
	file_org_xrpl_rpc_v1_ledger_proto_depIdxs = nil
}
