if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 12)
    message(FATAL_ERROR "Clang 12+ required for building clio")
  endif()
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 12)
    message(FATAL_ERROR "AppleClang 12+ required for building clio")
  endif()
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 11)
    message(FATAL_ERROR "GCC 11+ required for building clio")
  endif()
else()
  message(FATAL_ERROR "Supported compilers: AppleClang 12+, Clang 12+, GCC 11+")
endif()
