if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 16)
        message(FATAL_ERROR "Clang 16+ required for building clio")
    endif()
    set(is_clang TRUE)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 15)
        message(FATAL_ERROR "AppleClang 15+ required for building clio")
    endif()
    set(is_appleclang TRUE)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 12)
        message(FATAL_ERROR "GCC 12+ required for building clio")
    endif()
    set(is_gcc TRUE)
else()
    message(
        FATAL_ERROR
        "Supported compilers: AppleClang 15+, Clang 16+, GCC 12+"
    )
endif()
