name: Build clio
description: Build clio in build directory

inputs:
  targets:
    description: Space-separated build target names
    default: all
  subtract_threads:
    description: An option for the action get-threads-number.
    required: true
    default: "0"

runs:
  using: composite
  steps:
    - name: Get number of threads
      uses: ./.github/actions/get-threads-number
      id: number_of_threads
      with:
        subtract_threads: ${{ inputs.subtract_threads }}

    - name: Build targets
      shell: bash
      run: |
        cd build
        cmake \
          --build . \
          --parallel "${{ steps.number_of_threads.outputs.threads_number }}" \
          --target ${{ inputs.targets }}
