name: Build clio
description: Build clio in build directory

inputs:
  targets:
    description: Space-separated build target names
    default: all
  nproc_subtract:
    description: The number of processors to subtract when calculating parallelism.
    required: true
    default: "0"

runs:
  using: composite
  steps:
    - name: Get number of processors
      uses: XRPLF/actions/.github/actions/get-nproc@046b1620f6bfd6cd0985dc82c3df02786801fe0a
      id: nproc
      with:
        subtract: ${{ inputs.nproc_subtract }}

    - name: Build targets
      shell: bash
      env:
        CMAKE_TARGETS: ${{ inputs.targets }}
      run: |
        cd build
        cmake \
          --build . \
          --parallel "${{ steps.nproc.outputs.nproc }}" \
          --target ${CMAKE_TARGETS}
