services:
  clio_develop:
    image: ghcr.io/xrplf/clio-ci:067449c3f8ae6755ea84752ea2962b589fe56c8f
    volumes:
      - clio_develop_conan_data:/root/.conan2/p
      - clio_develop_ccache:/root/.ccache
      - ../../:/root/clio
      - clio_develop_build:/root/clio/build_docker
    working_dir: /root/clio/build_docker
    tty: true

volumes:
  clio_develop_conan_data:
  clio_develop_ccache:
  clio_develop_build:
