name: Check new libXRPL

on:
  repository_dispatch:
    types: [check_libxrpl]

concurrency:
  # Only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CONAN_PROFILE: gcc

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Clio / `libXRPL ${{ github.event.client_payload.version }}`
    runs-on: heavy
    container:
      image: ghcr.io/xrplf/clio-ci:14342e087ceb8b593027198bf9ef06a43833c696

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Prepare runner
        uses: XRPLF/actions/prepare-runner@2cbf481018d930656e9276fcc20dc0e3a0be5b6d
        with:
          enable_ccache: false

      - name: Update libXRPL version requirement
        run: |
          sed -i.bak -E "s|'xrpl/[a-zA-Z0-9\\.\\-]+'|'xrpl/${{ github.event.client_payload.conan_ref }}'|g" conanfile.py
          rm -f conanfile.py.bak

      - name: Update conan lockfile
        run: |
          conan lock create . --profile:all ${{ env.CONAN_PROFILE }}

      - name: Run conan
        uses: ./.github/actions/conan
        with:
          conan_profile: ${{ env.CONAN_PROFILE }}

      - name: Run CMake
        uses: ./.github/actions/cmake
        with:
          conan_profile: ${{ env.CONAN_PROFILE }}

      - name: Build Clio
        uses: ./.github/actions/build-clio

      - name: Strip tests
        run: strip build/clio_tests

      - name: Upload clio_tests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: clio_tests_check_libxrpl
          path: build/clio_tests

  run_tests:
    name: Run tests
    needs: build
    runs-on: heavy
    container:
      image: ghcr.io/xrplf/clio-ci:14342e087ceb8b593027198bf9ef06a43833c696

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: clio_tests_check_libxrpl

      - name: Run clio_tests
        run: |
          chmod +x ./clio_tests
          ./clio_tests

  create_issue_on_failure:
    name: Create an issue on failure
    needs: [build, run_tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create an issue
        uses: ./.github/actions/create-issue
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          labels: "compatibility,bug"
          title: "Proposed libXRPL check failed"
          body: >
            Clio build or tests failed against `libXRPL ${{ github.event.client_payload.conan_ref }}`.

            PR: ${{ github.event.client_payload.pr_url }}
            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/
