name: Check PR title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [develop]

jobs:
  check_title:
    uses: XRPLF/actions/.github/workflows/check-pr-title.yml@a5d8dd35be543365e90a11358447130c8763871d
