name: On clang-tidy auto fixes merged
on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  on_fix_merge:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[CI] clang-tidy auto fixes') }}
    runs-on: ubuntu-20.04

    permissions:
      actions: write

    steps:
      - name: Run clang-tidy workflow
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh workflow run clang-tidy.yml
