name: Documentation
on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    continue-on-error: true
    container:
      image: rippleci/clio_ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          lfs: true

      - name: Build docs
        run: |
          mkdir -p build_docs && cd build_docs
          cmake ../docs && cmake --build . --target docs
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build_docs/html
          name: docs-develop
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: docs-develop
