name: Documentation
on:
  push:
    branches: [release/*, develop]
  pull_request:
    branches: [release/*, develop]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    container:
      image: rippleci/clio_ci:latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docs
        run: |
          mkdir -p build_docs && cd build_docs
          cmake ../docs && cmake --build . --target docs
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build_docs/html
          name: develop # TODO: use x.y.z for `release/x.y.z` branches and `develop` for latest dev docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
