name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  run-hooks:
    uses: XRPLF/actions/.github/workflows/pre-commit.yml@9307df762265e15c745ddcdb38a581c989f7f349
    with:
      runs_on: heavy
      container: '{ "image": "ghcr.io/xrplf/clio-pre-commit:14342e087ceb8b593027198bf9ef06a43833c696" }'
