name: Pre-commit auto-update

on:
  schedule:
    # every first day of the month
    - cron: "0 0 1 * *"
  pull_request:
    branches: [release/*, develop]
    paths:
      - ".pre-commit-config.yaml"
  workflow_dispatch:

jobs:
  auto-update:
    uses: XRPLF/actions/.github/workflows/pre-commit-autoupdate.yml@5e942d61bf32f7557a7c159cfac4712a687b3e3a
    with:
      sign_commit: true
      committer: "Clio CI <skuznetsov@ripple.com>"
      reviewers: "godexsoft,kuznetsss,mathbunnyru"
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.ACTIONS_GPG_PASSPHRASE }}
