name: Create release

on:
  push:
    tags:
      - "*.*.*"
  pull_request:
    paths:
      - .github/workflows/release.yml

concurrency:
  # Only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos15
            conan_profile: apple-clang
            build_type: Release
            static: false
          - os: heavy
            conan_profile: gcc
            build_type: Release
            static: true
            container: '{ "image": "ghcr.io/xrplf/clio-ci:213752862ca95ecadeb59a6176c3db91a7864b3e" }'

    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs_on: ${{ matrix.os }}
      container: ${{ matrix.container }}
      conan_profile: ${{ matrix.conan_profile }}
      build_type: ${{ matrix.build_type }}
      static: ${{ matrix.static }}
      run_unit_tests: true
      run_integration_tests: true
      upload_clio_server: true
      download_ccache: false
      upload_ccache: false
      expected_version: ${{ github.event_name == 'push' && github.ref_name || '' }}

  release:
    needs: build-and-test
    uses: ./.github/workflows/reusable-release.yml
    with:
      overwrite_release: false
      prerelease: ${{ contains(github.ref_name, '-') }}
      title: "${{ github.ref_name }}"
      version: "${{ github.ref_name }}"
      header: >
        ${{ contains(github.ref_name, '-') && '> **Note:** Please remember that this is a release candidate and it is not recommended for production use.' || '' }}
      generate_changelog: ${{ !contains(github.ref_name, '-') }}
      draft: ${{ !contains(github.ref_name, '-') }}
