name: Trigger clio-ci
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  dispatch_build_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send build_packages repository_dispatch event to clio-ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
              -H 'Accept: application/vnd.github.v3+json' \
              "https://api.github.com/repos/legleux/clio-ci/dispatches" \
              -d '{"event_type": "build", "client_payload": {"branch":"${{ github.ref_name }}", "SHA": "${{ github.sha }}"}}'

      - name: Wait on result
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          INPUT_OWNER: legleux
          INPUT_REPO: clio-ci
          INPUT_WORKFLOW_FILE_NAME: "ci.yml"
        run: |
          # Find the id of the last build
          set -uxv
          last_workflow="null"
          while [[ "$last_workflow" == "null" ]]
          do
            last_workflow=$(curl -s -X GET "https://api.github.com/repos/${INPUT_OWNER}/${INPUT_REPO}/actions/workflows/${INPUT_WORKFLOW_FILE_NAME}/runs?event=repository_dispatch&status=queued" \
              -H 'Accept: application/vnd.github.v3+json' \
              -H "Authorization: Bearer ${INPUT_GITHUB_TOKEN}" | jq '[.workflow_runs[]] | first')
          done
          url=$(echo $last_workflow | jq .html_url)
          echo "Waiting on: $url"
          last_workflow_id=$(echo $last_workflow | jq '.id')
          echo "The workflow id is [$last_workflow_id]."
          echo ""
          conclusion=$(echo $last_workflow | jq '.conclusion')
          status=$(echo $last_workflow | jq '.status')
          wait_interval=120
          while [[ $conclusion == "null" && $status != "\"completed\"" ]]
          do
            echo "Waiting for job  for $wait_interval seconds"
            sleep $wait_interval
            workflow=$(curl -s -X GET "https://api.github.com/repos/$INPUT_OWNER/$INPUT_REPO/actions/workflows/$INPUT_WORKFLOW_FILE_NAME/runs" \
              -H 'Accept: application/vnd.github.v3+json' \
              -H "Authorization: Bearer $INPUT_GITHUB_TOKEN" | jq '.workflow_runs[] | select(.id == '$last_workflow_id')')
            conclusion=$(echo $workflow | jq '.conclusion')
            status=$(echo $workflow | jq '.status')
            echo "Checking conclusion [$conclusion]"
            echo "Checking status [$status]"
          done

          if [[ $conclusion == "\"success\"" && $status == "\"completed\"" ]]
          then
            echo "Yes, success"
          else
            echo "Job ${conclusion}!."
            exit 1
          fi
